### ISSUE TITLE
Prompt customization

### ISSUE THREAD

**Issue by mcheung610** [segersniels/propr-cli#5]
Can we support changing the [prompt](https://github.com/segersniels/propr-cli/blob/master/src/utils/openai.rs#L51) from the config command? `propr config prompt`

**Comment by segersniels** [comment]
> Can we support changing the [prompt](https://github.com/segersniels/propr-cli/blob/master/src/utils/openai.rs#L51) from the config command? `propr config prompt`

That definitely seems reasonable. Feel free to create a PR if you're up to make the change yourself. 
You can base yourself on how the template is currently adjusted.

**Comment by segersniels** [comment]
@mcheung610 Can you have a look at #6 if that would be sufficient for your use case?

**Comment by segersniels** [comment]
I am also looking into adding initial support for custom assistants. That way users can have external control over their system message and which model they want to use.
